version: "3.9"

services:
  web:
    build: .
    container_name: journal_flask
    command: python main.py
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - chroma_data:/app/data/chroma_journal


  celery:
    build: .
    container_name: journal_celery
    command: celery -A app.celery_app.celery worker -l info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - chroma_data:/app/data/chroma_journal


  redis:
    image: redis:7
    container_name: journal_redis
    ports:
      - "6379:6379"
  

volumes:
  chroma_data:
